name: 'Deploy to S3 JavaScript'
description: 'Deploy built website to S3 bucket'
runs:
  using: 'node20'
  main: 'index.cjs'
inputs:
  bucket:
    description: 'S3 bucket name'
    required: true
  region:
    description: 'AWS region'
    required: true
    default: 'us-east-1'
  dist-folder:
    description: 'Folder with built website'
    required: true
    default: 'dist'